# Generated by Django 4.0.6 on 2022-08-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='size',
            field=models.CharField(choices=[('MICRO', 'MICRO'), ('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM')], default='MICRO', max_length=20),
            preserve_default=False,
        ),
    ]
