# Generated by Django 4.0.6 on 2022-08-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_employee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
