# Generated by Django 4.0.6 on 2022-07-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_reset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
