# Generated by Django 4.0.6 on 2022-08-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_loans', 'Can Create Loans')]},
        ),
    ]
