# Generated by Django 4.0.6 on 2022-08-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_user_nin_file_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bvn',
            field=models.PositiveIntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nin',
            field=models.PositiveIntegerField(max_length=11, null=True),
        ),
    ]
