# Generated by Django 4.0.6 on 2022-08-27 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0005_alter_user_middle_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_applied', models.DateTimeField()),
                ('time_payed', models.DateField()),
                ('is_payed', models.DateTimeField()),
                ('time_to_pay', models.DateTimeField()),
                ('number_of_employee', models.PositiveIntegerField()),
                ('is_given', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficiary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Purchase', 'Purchase'), ('Expenses', 'Expenses'), ('Tax', 'Tax'), ('Income', 'Income')], default='', max_length=45, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cost_price_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('program_title', models.CharField(max_length=200)),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('MICRO', 'MICRO'), ('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM')], max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('paying_days', models.PositiveIntegerField()),
                ('grace_period', models.PositiveIntegerField()),
                ('collateral', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiaries', models.ManyToManyField(to='Loans.beneficiaries')),
                ('fsp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fsp', to=settings.AUTH_USER_MODEL)),
                ('sectors', models.ManyToManyField(to='Users.sector')),
            ],
        ),
        migrations.CreateModel(
            name='FSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fsp_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Profit')),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('records', models.ManyToManyField(blank=True, to='Loans.record')),
                ('sales_records', models.ManyToManyField(blank=True, to='Loans.salesrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
