# Generated by Django 4.0.6 on 2022-07-25 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FSP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('program_title', models.CharField(max_length=200)),
                ('size', models.CharField(choices=[('MICRO', 'MICRO'), ('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM')], max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('number_of_employee', models.PositiveIntegerField()),
                ('amount', models.PositiveBigIntegerField()),
                ('paying_days', models.PositiveIntegerField()),
                ('grace_period', models.PositiveIntegerField()),
                ('collateral', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiaries', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('fsp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Loans.fsp')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Loans.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_applied', models.DateTimeField()),
                ('time_payed', models.DateField()),
                ('is_payed', models.DateTimeField()),
                ('time_to_pay', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
