# Generated by Django 4.0.6 on 2022-07-27 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('program_title', models.CharField(max_length=200)),
                ('size', multiselectfield.db.fields.MultiSelectField(choices=[('MICRO', 'MICRO'), ('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM')], max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('paying_days', models.PositiveIntegerField()),
                ('grace_period', models.PositiveIntegerField()),
                ('collateral', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiaries', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('fsp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fsp', to=settings.AUTH_USER_MODEL)),
                ('sectors', models.ManyToManyField(to='Users.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_applied', models.DateTimeField()),
                ('time_payed', models.DateField()),
                ('is_payed', models.DateTimeField()),
                ('time_to_pay', models.DateTimeField()),
                ('number_of_employee', models.PositiveIntegerField()),
                ('is_given', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='beneficiary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
