# Generated by Django 4.0.6 on 2022-07-25 13:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='sector',
        ),
        migrations.AddField(
            model_name='loan',
            name='sectors',
            field=models.ManyToManyField(to='Loans.sector'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MICRO', 'MICRO'), ('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM')], max_length=100),
        ),
    ]
