# Generated by Django 4.0.6 on 2022-08-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='requiremenent',
            new_name='requirement',
        ),
    ]
