# Generated by Django 4.0.6 on 2022-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0002_remove_loan_sector_loan_sectors_alter_loan_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='number_of_employee',
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='is_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiaries',
            name='number_of_employee',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
