# Generated by Django 4.0.6 on 2022-07-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0003_remove_loan_number_of_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
