# Generated by Django 4.0.6 on 2022-07-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0004_alter_beneficiaries_user_alter_loan_fsp_delete_fsp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaries',
            name='is_given',
        ),
    ]
