# Generated by Django 4.0.6 on 2022-07-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_sector'),
        ('Loans', '0006_beneficiaries_is_given'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sector',
        ),
        migrations.AlterField(
            model_name='loan',
            name='sectors',
            field=models.ManyToManyField(to='Users.sector'),
        ),
    ]
