# Generated by Django 4.0.6 on 2022-07-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0001_initial'),
    ]

    operations = [
    ]
