# Generated by Django 4.0.6 on 2022-07-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0003_remove_lesson_finished_lesson_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontranslation',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d/'),
        ),
    ]
