# Generated by Django 4.0.6 on 2022-07-20 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lessons', '0006_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='correct',
            field=models.ManyToManyField(blank=True, related_name='right', to='Lessons.quiz'),
        ),
        migrations.AlterField(
            model_name='score',
            name='wrong',
            field=models.ManyToManyField(blank=True, related_name='wrong', to='Lessons.quiz'),
        ),
    ]
