# Generated by Django 4.0.6 on 2022-07-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lessons', '0007_score_user_alter_score_correct_alter_score_wrong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='type',
            new_name='answer',
        ),
    ]
